### ISSUE TITLE
Hvor lenge kan denne kjøre

### ISSUE THREAD

**Issue by audunhauge** [SveinIsdahl/Sveinisdahl.github.io#2]
Ser at du pusher posisjoner inn i array
Går du tom for plass etter hvor lang tid ?
Hva er frameraten - kan den styres ?
p5 ser veldig greit ut

**Comment by SveinIsdahl** [comment]
Framerate er i utgangspunktet 60, men kan reguleres med framerate(30) ned til 30 f.eks. Men den går ned jo lengre programmet kjører. p5 er veldig nyttig for canvas o.l.

**Comment by SveinIsdahl** [comment]
Jo flere elementer i array, jo mer krevende er det for prosessor

**Comment by audunhauge** [comment]
Du kunne kanskje lagre bare de tusen siste posisjonene.
Da har du en  let idx = 0 ved start
pos[idx] = verdi;
idx = (idx +1 ) % 1000;   
// idx er da sequence 0,1,2, ...  ,998,999,0,1, ...
Du vil da overskrive eldre posisjoner etter at 1000 er plassert på skjermen.
Slipper fall i framerate pga stor array

**Comment by SveinIsdahl** [comment]
lagde min egen versjon av det du beskriver tidligere i dag, men fikk fortsatt 90 grader cpu og vifte på fullt. Hvis jeg gjør arrayet for lite så blir det mer enn slange enn ett mønster. 
   if (array_x.length > 1000){
        array_x.shift();
        array_y.shift();
    }
Vet ikke hvordan min kode sammenligner med din på effektivitet.
Skal prøve med litt lavere tall for å se hvordan det blir.

**Comment by audunhauge** [comment]
Ikke sikker, men din metode ser ut som den vil påføre
mye stress på minne (reclame/release).
Du bruker ikke samme minne omigjen, du
krever nytt minne i ene enden (push) og frigir i den andre (shift).
Da må minne-allocatoren jobbe hele tida.
Løsningen med idx = (idx + 1) % MaxSize vil la arrayet vokse til MaxSize
og deretter bruke den samme arrayen omigjen (uten jobb for allocatoren).
MaxSize kan godt være 10000 - det som stresser maskinen med denne løsningen 
er ikke bruk av minne, men at du tegner så mange sirkler hver frame.
